[RSDK-10919] moving over obstacles-pointcloud and obstacles-depth from RDK (#3)
* first test with new vision service function

* moved over er_ccl_clustering.go from rdk, made obstacles-pointcloud struct not trivially config

* make sure validate() method implemented, fix package naming

* go fmt

* local test changes, one not working, but fine on viam app

* readme added in

* meta.json updated

* PR feedback changes

* go fmt, pr changes still work on app.viam

* variabl rename

* remove vector from config and readme

* defaults and out of bounds behavior set

* yml and meta changes

---------

Co-authored-by: AGanguly13 <adwaitganguly@viam.com>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,20 +1,33 @@
-# see https://github.com/viamrobotics/build-action for help
 on:
-  push:
-    tags:
-      - "[0-9]+.[0-9]+.[0-9]+" # the build-action will trigger on tags with the format 1.0.0
+  release:
+    types: [published]
 
 jobs:
-  publish:
+  validate-tag:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - uses: viamrobotics/build-action@v1
+      - name: Validate tag format
+        run: |
+          TAG="${{ github.event.release.tag_name }}"
+          echo "Validating tag: $TAG"
+          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
+            echo "Tag matches semver."
+          else
+            echo "Error: tag does not match semvar"
+            exit 1
+          fi
+
+  publish:
+    needs: validate-tag
+    name: Build and Upload module
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Build and Publish
+        uses: viamrobotics/build-action@v1.4
         with:
-          # note: you can replace this line with 'version: ""' if
-          # you want to test the build process without deploying
-          version: ${{ github.ref_name }}
+          version: ${{ github.event.release.tag_name }}
           ref: ${{ github.sha }}
           key-id: ${{ secrets.viam_key_id }}
           key-value: ${{ secrets.viam_key_value }}
-          token: ${{ github.token }} # only required for private git repos
